# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='work',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.AlterField(
            model_name='line',
            name='poem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Poem'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Book'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Author'),
        ),
    ]
