# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170422_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
