# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170422_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='poem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.Poem'),
        ),
    ]
