# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170422_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='work',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.Work'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='api.Book'),
        ),
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='api.Author'),
        ),
    ]
