# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170422_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='api.Author'),
        ),
    ]
